# Generated by Django 4.2.4 on 2023-08-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicall",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
